apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgBfOgWT9XuUvAoSbNBhmgYoC4vbvWyzrVylPTLpfNrz5HUDvYpuODIZ/tE/qxdoI+rgIDRCfCr+3nFb2gd35BXwSUFALAS6P6G4Z3DBNpc7u1O/I0s6lCifvlUnrMqhf0ICI/kxhHG91cZV75afU1jQ/vnsKUcWt8rMB6DKvWAAe2rTCsIZreG6c7FviMEJfvVHaGAUiiv1cFcm7rUBzUzasl8meBZV70g/0a/gPLpmGuCeIW9yICG2kx6oOGfiqvwdZ54h0RomNQVv2eiF8ri3lO4UJkc/3lL/nZfxGmaZ6iI8lEuRMM++nHmnu+sPEl9KvHJbg2PAL1dwUwmp01VbMfGuhMPS+6SOmM5y0chXtj5x2W1Ur8udW6lOTh+26CdbWxvVxazgLQ+Z4098HNdTwzmSETHaKJVze4ttoH63wk17aUW6a3JsB73ZGuCT66yOFkFnulDpK7lY+X4JIhqdXaQFB06UhPX5fv6fsTpeHKVt6IvRuDNGnLS4L/Ta+55TGC1R9DslqDJZSiMXIOZQFp8pfz/tXq25hdpw9unypx9GBt4yKIIfXHe3Xcd8eueyjUdqCp65FmcLYELb5kGabo4+8jlFy8GniytEY3k4TQ0wuf5XHNGZwzi5CGd7z4yVGiOE0PEf1xBekpjK5U8fDY56Zj/p8FJ+J8gIu0gUMTqgBusc0ReKlDpGTHM62Y/pNBkIdHfbgL7O4QezvbMa6Zw7OF5zyqMSdvQRWjtkZoZMwNPcitZQAsNP
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

