apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgAWoRQScpDDN81QKC1jCedAEU9KbkcQtkvx1cgP2fIUrG8SaekaNXj4NmXMfQZ7fWSfpnoQHpivv2vmdzK71Zu06aiM1t1Mu5FBHkKdHgt2pjBlrheyA59JxCsoLEZE9kschxMvYbU+pOLRPq4cknY9F/6MjcUY+wPfLCtJZ7/P41TiGr0nqcs0dExq+QWDa28DmtproCtSQ7Vljerg09gZdhJwq+IEcqeAKDuJVwu+pTwkQJgtkUCBlD4sKWEgNkBj0wLIXua2Elws3gXCLQct3OWROuwjURTs8AM21DWhXElBdOBo/EPShzX5ImMh7nxVUBHVsZNmjyfhYDcpgq5pzZlbN7kFV25rZmHpJBSTVTy8IDZGXn9MtX+3Xis3CJKyAPbLLEh65QsanYru2M1AnA9xWOIwkdYTbEmDT8EgPXBNXEVmLa+flz3kbnYWgxXhXdx0YTt+ZAc9IzQRUNa/JxXbE7O/SlPybfBrFpEgi3DYAb1MdDLSJGkKNUKd19hsfYsN1v+rBj6h63EFZc8GimaeauAuwW9jes8SsieTfvrF19UV2tPc7bGNqn9zkSTfRl7fSsg8PPmMumGuCsB9VF1IFYhoT+smGW5Zon06ZTEI8EvZeBkKsXarQDIqm8bA5/0JLE6/QS4CjbrLUgcjkkJGq2EZSxs1oY7eEWt7YXqYgGbxRVChaTfExDXEAk9ESe9k2eNuDnLZA3jqtesC+xcL3P1QpEn0PX8Xxu5vsELIjhbuXvwmzjnF
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

