apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgBlkfKi00zXp7+xegIwm/sZ/shsUXYCfmfv9d3R5cAbC0hKN/PZV5MRzQi3puPeUn3F4C2AROJK1JDXgwwfj5LyNuhWFlHMUwP8jhd0ZQXoZSaYp8jGCsqjoiSQmh/ByS5YKsXgxPpUN4m0f34jo+Ab4Dme5iulyL5ViqkgWC78K0XRt60cKGyReN2eoE+A35XjkNnqn6RLQSWiqgZLo5WvF5qMyWLKRYs9EHGQCi8mIzEi2ZgF5MBbgsfUhTzCsUOnySvKqriN+2bRBC0/5r8CqajrWzNCC7L18tLWf9FZ9O5HLz7wgCctpfzxtnQIElLNSJrrxazcu1V5yOqYNPgrwEIJq7YeMD99zpRzZFtROXtcLlLlXLaHZ+wH1NaYc/2Pa8dyEk4HneVNAoxHpqQFaTGtBzxmL3gKopXak0mJWI0Q8PZGry5sgQxs4HbQNL97n+RR6u3CI/tnvVABcpA3Boee1sVdmbjjOGYal4Ob1F4YVeoj8+35o3ovMx4Q4qf3ThebFtvKEqYXTYcfZp58xSN7Ysl+TJkIO6MJnea7olV8O+3gH2y1U/zpzZG2awq8Iq7lVtsp4r8ZP4TKsZ0iZ07tGjHANNOwjJZnuOoxMh0RUCMa88pqiDOUVXjLgypEMxBX+88pAYnvTwwQFeWZ6OOwirGPk54RNcRS9w2TQCrSbRYIw4NLKeTcEeTTIxRwAUQZDUzDqO6X4gMymj93wEDXR81037mUeM5FiqD79YQkcsA1bcntt4xN
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

