apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgCLTWCbNcg32b5glmAheUqX9QnjY/BJpDmdalOSD4QZ5XdAf0ZvAYE1kf+ni+pr28phJw7+kSgBskc1g60H2v9y0oBr+hgc20vCK8TdG2EODywOdb81l6/ilyENJuitmWTz0d6oDRpW7xnXrktQy0kvL/J5RelVdomGXftgcqThpkDsycyI4sN98r83dP2M+FjZXsSjM7mApRqSn0s2dfXH7qwUyEGkPmcLX4I7vJZ3CaR3dUE5IJQqDwJw6LwsmDKK5sdGi5/bd7GNvGM1w5DXOK28YFJwHU3wPNBDLKHpyUk3E9EyPxl/8z5OeilLX4aG9l/ZwOJvk0vIFUJ8qm1/oKn5dqP9WtHLjG4BNOcLn4JDH0yVM3wUbX4v5VdKVqCG+LvuhbRPd0ECFAQ1nSNl9ghlAwZWeuTzIgFfVZDqAskmZNNJsXWMdJoAMWIJtA/h+x1KlUqd0R3eRv4F6XvQc7vuPh6mPjvnqc+oaGpVAh6evbAnO9TLaeh1oszD9X2jPj0pb12Yx4QUGNg6UUWTBCI2RBOtRuNtD+e5MCUvTXriiQn819IQeAVjyjO7ZEgN1apJN1PaHfhMNWtElk6LmYhdrfu7xhR+ucDIji7hvXmccHwiiN5po4ATIDo5XfEwSYnnAFnv08s3OcShz09fR5iO7vPt9/4pGA2ukDxKmZWvIPDUya3xaccj0wverYPv8U5LGsV88k3i1SxPYkWcWOMBVhIEPFYR+pq0Xyp/JZck/xbn+s48vntw
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

